def help_file() {
    log.info """
    #######################################################################################
    ########### MERGE AND REFORMAT INPUT FILES; CREATE CONFIG FOR DToL PIPELINE ###########
    #######################################################################################

        --yaml <PATH/TO/YAML/FILE>
                Path to the .yaml file generated by the data mapper query

        --outdir <PATH/TO/OUTPUT/DIRECTORY>
                File path to where reads and config file should be stored

        --longread_indir
                Path to directory containing PacBio read files for DToL's genomeassembly
                pipeline.
                Default is './results/processed_reads/hifi'

        --hic_indir
                Path to directory containing Hi-C read files for DToL's genomeassembly
                pipeline.
                Default is './results/processed_reads/hic'
        
    #######################################################################################
    """.stripIndent()
}

if (params.remove('help')) {
    help_file()
    exit 0
}

// check no unexpected parameters were specified
allowed_params = [
    // pipeline inputs
    "yaml",
    "outdir",
    "longread_indir",
    "hic_indir",
    // "sample_id",

    // "scientific_name",
    // "busco_lineage",
    // "busco_version",
    // "mito_min_length",
    // "mito_code",
    // "hic_motif",
    // "hic_aligner",

    // Pawsey options
    "max_cpus",
    "max_memory"
]

params.each { entry ->
    if ( !allowed_params.contains(entry.key) ) {
        println("The parameter <${entry.key}> is not known");
        exit 0;
    }
}

// if ( !params.sample_id ) {
//     throw new IllegalArgumentException("no --sample_id specified")
// }

include { CONCAT_PACBIO_FASTQ } from './modules/concat_pacbio_fastq.nf'
include { CONCAT_PACBIO_BAM } from './modules/concat_pacbio_bam.nf'
include { CONCAT_HIC_READS } from './modules/concat_hic_reads.nf'
include { CREATE_CONFIG_FILE } from './modules/create_config_file.nf'


// check longread files are all the same file type
def longread_files = file(params.longread_indir)
def input_longreads = longread_files.listFiles().findAll { it.name.endsWith('.bam') || it.name.endsWith('.fastq.gz') }

if (!input_longreads) {
    throw new IllegalArgumentException("❌ No input long-read files found!")
}

// --- get extensions ---
def unique_exts = input_longreads.collect { f ->
    f.name.endsWith('.fastq.gz') ? 'fastq.gz' :
    f.name.endsWith('.bam')      ? 'bam' :
    f.extension
}.unique()

if (unique_exts.size() > 1) {
    throw new IllegalArgumentException("❌ Multiple file types detected in long-read inputs: ${unique_exts.join(', ')}")
}

println "✅ Detected long-read file type: ${unique_exts[0]}"


// see whether hi-c reads exist
def hic_reads = file(params.hic_indir)

def input_hic = (hic_reads.exists() && hic_reads.isDirectory()) ?
                 hic_reads.listFiles()?.findAll { it.isFile() } :
                 []

if (!input_hic) {
    log.warn "hic reads directory does not exist or is empty - are you running an assembly without scaffolding?"
} else {
    log.info "✅ Found ${input_hic.size()} hic files in '${hic_reads}'"
}

def readYAML(yamlfile) {
    return new org.yaml.snakeyaml.Yaml().load(yamlfile.text)
}

workflow {

    // read in the yaml file
    def yaml_data = readYAML(file(params.yaml))

    pacbio_samples = yaml_data.reads.PACBIO_SMRT

    if ( !pacbio_samples ) { 

        pacbio_samples_ch = []

    } else {

        pacbio_samples_reformatted = pacbio_samples
            .collectMany { pkg, pkgData ->
                pkgData.collect { file ->

                    def basename = file.name.getBaseName(1)
                    def file_path = "${params.longread_indir}"+basename+".trim.fastq.gz"
                    [
                        package: pkg,
                        file_name: file.name,
                        format: file.format,
                        url: file.url,
                        md5sum: file.md5sum,
                        lane: [],
                        read: [],
                        file: file_path
                    ]

                }
            }

        pacbio_samples_ch = Channel.from(pacbio_samples_reformatted)

        pacbio_samples_ch.view()
        
        // check each input file exists; throw error if not
        pacbio_samples_ch
            .map { file_info ->
                    if ( !file(file_info.file).exists() ) { error(
                    """
                    ERROR: ${file_info.file} does not exist. Check \'--indir\' is correct
                    """
                    )
                } 
            }
    }

    /////////////////////////////


//    // input channels
//    hic_reads_ch = input_hic ? Channel.fromPath(input_hic) : Channel.empty()

//    pacbio_reads_ch = Channel.fromPath(input_longreads)


//     // process pacbio reads
//     concat_pacbio_reads_ch = pacbio_reads_ch.collect()

//     if (unique_exts[0] == 'bam') {
//         CONCAT_PACBIO_BAM(concat_pacbio_reads_ch)
//         pacbio_config_ch = CONCAT_PACBIO_BAM.out.processed_pacbio
//     } else if (unique_exts[0] == 'fastq.gz') {
//         CONCAT_PACBIO_FASTQ(concat_pacbio_reads_ch)
//         pacbio_config_ch = CONCAT_PACBIO_FASTQ.out.processed_pacbio
//     } else {
//         error("unrecognised file type: ${unique_exts[0]}. How did you even get here?")
//     }

//     //process any hic reads
//     if (input_hic) {
//         concat_hic_reads_ch = hic_reads_ch.collect()
//         CONCAT_HIC_READS(concat_hic_reads_ch)    
//         hic_config_ch = CONCAT_HIC_READS.out.cram
//     } else {
//         hic_config_ch = file("${projectDir}/assets/dummy_hic")
//     }

//     def yaml_data = file(params.yaml)

//     // create config file
//     CREATE_CONFIG_FILE(yaml_data, pacbio_config_ch, hic_config_ch)
    
}
