def help_file() {
    log.info """
    #######################################################################################
    ########### MERGE AND REFORMAT INPUT FILES; CREATE CONFIG FOR DToL PIPELINE ###########
    #######################################################################################

        --yaml <PATH/TO/YAML/FILE>
                Path to the .yaml file generated by the data mapper query

        --outdir <PATH/TO/OUTPUT/DIRECTORY>
                File path to where read files and config.yaml should be stored
                Default is './results/genomeassembly_inputs'

        --longread_indir
                Path to directory containing long-read files for DToL's genomeassembly
                pipeline.
                Default is './results/processed_reads/hifi'

        --hic_indir
                Path to directory containing Hi-C read files for DToL's genomeassembly
                pipeline.
                Default is './results/processed_reads/hic'
        
    #######################################################################################
    """.stripIndent()
}

if (params.remove('help')) {
    help_file()
    exit 0
}

// check no unexpected parameters were specified
allowed_params = [
    // pipeline inputs
    "yaml",
    "outdir",
    "longread_indir",
    "hic_indir",

    // Pawsey options
    "max_cpus",
    "max_memory"
]

params.each { entry ->
    if ( !allowed_params.contains(entry.key) ) {
        println("The parameter <${entry.key}> is not known");
        exit 0;
    }
}

include { CONVERT_PACBIO } from './modules/convert_pacbio.nf'
include { FORMAT_CONFIG_FILE } from './modules/format_config_file.nf'

// include { CONCAT_PACBIO_FASTQ } from './modules/concat_pacbio_fastq.nf'
// include { CONCAT_PACBIO_BAM } from './modules/concat_pacbio_bam.nf'
// include { CONCAT_HIC_READS } from './modules/concat_hic_reads.nf'
// include { CREATE_CONFIG_FILE } from './modules/create_config_file.nf'

// // check longread files are all the same file type
// def longread_files = file(params.longread_indir)
// def input_longreads = longread_files.listFiles().findAll { it.name.endsWith('.bam') || it.name.endsWith('.fastq.gz') }

// if (!input_longreads) {
//     throw new IllegalArgumentException("❌ No input long-read files found!")
// }

// // --- get extensions ---
// def unique_exts = input_longreads.collect { f ->
//     f.name.endsWith('.fastq.gz') ? 'fastq.gz' :
//     f.name.endsWith('.bam')      ? 'bam' :
//     f.extension
// }.unique()

// if (unique_exts.size() > 1) {
//     throw new IllegalArgumentException("❌ Multiple file types detected in long-read inputs: ${unique_exts.join(', ')}")
// }

// println "✅ Detected long-read file type: ${unique_exts[0]}"


// // see whether hi-c reads exist
// def hic_reads = file(params.hic_indir)

// def input_hic = (hic_reads.exists() && hic_reads.isDirectory()) ?
//                  hic_reads.listFiles()?.findAll { it.isFile() } :
//                  []

// if (!input_hic) {
//     log.warn "hic reads directory does not exist or is empty - are you running an assembly without scaffolding?"
// } else {
//     log.info "✅ Found ${input_hic.size()} hic files in '${hic_reads}'"
// }

def readYAML(yamlfile) {
    // getting the snakeyamlpackage from org.yaml: https://mvnrepository.com/artifact/org.yaml/snakeyaml
    // .Yaml.load() will load object the text from yamlfile
    return new org.yaml.snakeyaml.Yaml().load(yamlfile.text)
}

workflow {
    // read in the yaml file
    def yaml_data = readYAML(file(params.yaml))

    // not sure if that's the right syntax - don't throw error if PACBIO_SMRT reads can't be found
    pacbio_samples = yaml_data.reads?.PACBIO_SMRT

    if ( !pacbio_samples ) { 

        pacbio_samples_ch = []

    } else {

        pacbio_samples_reformatted = pacbio_samples
            .collectMany { pkg, pkgData ->
                pkgData.collect { file ->
                    def file_name = file.url.tokenize('/')[-1].replaceFirst(/\.bam$/, '.trim.fastq.gz')
                    def input_file_path = "${params.longread_indir}"+"/"+file_name 
                    def outfile_name = file_name.replaceFirst(/\.fastq.gz$/, '.fasta.gz')
                    def publish_path = "${params.outdir}"+"/reads/hifi/"+outfile_name
                    [
                        package: pkg,
                        file_name: file_name,
                        url: file.url,
                        md5sum: file.md5sum,
                        lane: [],
                        read: [],
                        file: input_file_path,
                        publish_path: publish_path
                    ]
                }
            }

        pacbio_samples_ch = Channel.from(pacbio_samples_reformatted)

        pacbio_samples_ch.view()
        
        // check the files exist where they're supposed to
        pacbio_samples_ch
            .map { file_info ->
                    if ( !file(file_info.file).exists() ) { error(
                    """
                    ERROR: ${file_info.file} does not exist. Check \'--longread_indir\' is correct
                    """.stripIndent()
                    )
                } 
            }

        // reformat data from fastq to fasta
        CONVERT_PACBIO(pacbio_samples_ch)

        // collect the output reads
        longread_files = CONVERT_PACBIO.out.pacbio_fa.collect()
        longread_files.view()

        //longread_files_ch = Channel.from(longread_files).join(',')
        //longread_files_ch.view()
        // convert the read paths to a big string
        //long_reads_str = longread_files.join(',')
        //long_reads_str.view()
    }
}

    /////////////////////////////


//    // input channels
//    hic_reads_ch = input_hic ? Channel.fromPath(input_hic) : Channel.empty()

//    pacbio_reads_ch = Channel.fromPath(input_longreads)


//     // process pacbio reads
//     concat_pacbio_reads_ch = pacbio_reads_ch.collect()

//     if (unique_exts[0] == 'bam') {
//         CONCAT_PACBIO_BAM(concat_pacbio_reads_ch)
//         pacbio_config_ch = CONCAT_PACBIO_BAM.out.processed_pacbio
//     } else if (unique_exts[0] == 'fastq.gz') {
//         CONCAT_PACBIO_FASTQ(concat_pacbio_reads_ch)
//         pacbio_config_ch = CONCAT_PACBIO_FASTQ.out.processed_pacbio
//     } else {
//         error("unrecognised file type: ${unique_exts[0]}. How did you even get here?")
//     }

//     //process any hic reads

    // hic_samples = yaml_data.reads?.'Hi-C'

    // if ( !hic_samples ) { 

    //     hic_samples_ch = []

    // } else {

    // hic_filepaths_ch = Channel.from(hic_samples.collect { sample_name, lanes ->

    //     // Extract R1 and R2 file lists
    //     r1_files = lanes.r1.collect {"${params.hic_indir}/${it.name.replaceAll(/\\.fq\\.gz$/, '.trim.fq.gz')}"}
    //     r2_files = lanes.r2.collect {"${params.hic_indir}/${it.name.replaceAll(/\\.fq\\.gz$/, '.trim.fq.gz')}"}

    //     // Zip R1 and R2 lanes together
    //     r1_files.zip(r2_files).collect { r1, r2 ->
    //         tuple(sample_name, r1, r2)
    //     }
    // }.flatten())

    //     // check the files exist where they're supposed to
    //     hic_filepaths_ch
    //         .map { file_info ->
    //                 if ( !file(file_info.file).exists() ) { error(
    //                 """
    //                 ERROR: ${file_info.file} does not exist. Check \'--hic_indir\' is correct
    //                 """.stripIndent()
    //                 )
    //             } 
    //         }    

// steps
// 1. check pacbio files exist (need longread_indir and yaml file)
// 2. convert fq.gz files to fa.gz - publish to outdir
// 3. check hic files exist (need --hic_indir and yaml file)
// 4. check no unexpected hic files exist
// 5. convert hic files to .cram - publish to outdir
// 6. populate config file with file paths and info



        // if(###HIC READS EXIST)
        // CONVERT_HIC(hic_filepaths_ch)
        // hic_files = CONVERT_HIC.out.collect()
        // #####

        // // if hic_reads exists, joing them otherwise leave blank
        // hic_reads_str = ?hic_files ? hic_files.join(','): ""

        // // format the config file
        // FORMAT_CONFIG_FILE(params.yaml, long_reads_str, hic_reads_str)

